# Generated by Django 4.0.3 on 2022-04-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rasm',
            field=models.ImageField(upload_to='rasmlar/'),
        ),
    ]
