# Generated by Django 4.0.3 on 2022-04-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tanlov',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
            preserve_default=False,
        ),
    ]
